[{DAY 13} NumPy 學習筆記(中） - iT 邦幫忙::一起幫忙解決難題，拯救 IT 人的一天](https://ithelp.ithome.com.tw/articles/10270218)

透過索引值提取單筆資料

一維陣列： [索引值] 只需要在括號裡加上索引值即可

In [2]:
import numpy as np
arr = np.array([1,2,3])
a=arr[2] #這裡想要取得索引值為2的數值
print(a)

3


二維陣列：[row, column] ([第一維的索引值, 第二維的索引值])

In [5]:
import numpy as np
#創建二維陣列
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

# 在二維陣列裡使用[row,column]，
# 前面放的是要取的第一個維度（row)，後面放的是第二個維度(column)
b=a[1,5] # 使用a[1,-2]也可取得同樣位置 ＃也可表示為a[1][5]
print(b)
c=a[1,-2]
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
13
13


透過切片取出特定元素內容：" : "

一維陣列：

In [7]:
import numpy as np
arr1 = np.arange(0, 10)
print(arr1)
'''array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])'''
arr2=arr1[5:] #想取得索引值為5之後所有的數值
'''array([5, 6, 7, 8, 9])'''
print(arr2)
arr3=arr1[:5] #想取得索引值為5之前的所有數值
'''array([0, 1, 2, 3, 4])'''
print(arr3)

[0 1 2 3 4 5 6 7 8 9]
[5 6 7 8 9]
[0 1 2 3 4]


二維陣列：

In [20]:
import numpy as np
#創建二維陣列
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)
print('---------------')
# 當我們要取得特定的row時
arr1=a[0,:]  # 在第二個維度選項時使用 ":"，可以取得第1個row裡所有的值
''' array([1, 2, 3, 4, 5, 6, 7])'''
print(arr1)
# 當我們要取得特定的column
arr2=a[:, 2]# 在第一個維度選項時使用 ":"，可以取得第2個column裡所有的值
'''array([ 3, 10])''' #第二列裡的兩個值就被取出來了
print(arr2)
# 橫向切片
arr3=a[:1]
'''array([[1, 2, 3, 4, 5, 6, 7]])'''
print(arr3)
print('---------------')
arr4=a[1,:]
print(arr4)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
---------------
[1 2 3 4 5 6 7]
[ 3 10]
[[1 2 3 4 5 6 7]]
---------------
[ 8  9 10 11 12 13 14]


按照指定間隔取值：[start index : end index: step size]

一維陣列

In [22]:
import numpy as np
#首先先建立一個1~12的一維陣列
prac = np.arange(13)
print(prac)

#若是我們想要他以偶數形式出現，step size設為2
even_num = prac[0:13:2]
'''[ 0  2  4  6  8 10 12]'''
print(even_num)

#若是想要出現0,4,8,12, stepsize要設為4
print(prac[0:13:4])
'''[ 0  4  8 12]'''

[ 0  1  2  3  4  5  6  7  8  9 10 11 12]
[ 0  2  4  6  8 10 12]
[ 0  4  8 12]


'[ 0  4  8 12]'

二維陣列

In [23]:
import numpy as np
# 在二維陣列中，我們先來看原本的a長怎樣
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)
'''[[ 1  2  3  4  5  6  7] [ 8  9 10 11 12 13 14]]'''

# 如果我們想要看到 2,4,6
# [從第一個row裡面去查, (start with 2:  end in 5: stepsize 2)] 
print(a[0, 1:6:2]) # 從後面開始算可以使用（-1) : a[0, 1:-1:2]
'''array([2, 4, 6])'''

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
[2 4 6]


'array([2, 4, 6])'

更新值：直接用索引值取代原本的值

In [25]:
import numpy as np
#創建二維陣列
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)
'''[[ 1  2  3  4  5  6  7] [ 8  9 10 11 12 13 14]]'''

#當我們想要把13換成200
a[1,5] = 200 # 13的索引值為[1,5]替換成200
'''[[  1   2   3   4   5   6   7]
 [  8   9  10  11  12 200  14]]'''

#當我們想要改掉整個row或是column
a[:,2] = 55 # 想要把第二個column改成55
'''[[  1   2  55   4   5   6   7]
 [  8   9  55  11  12 200  14]]'''
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
[[  1   2  55   4   5   6   7]
 [  8   9  55  11  12 200  14]]


刪除資料：np.delete(陣列名稱, 索引值, axis=None)

In [26]:
import numpy as np
# 首先創建任意數列
arr = np.arange(5,17)
print(arr)
'''[ 5  6  7  8  9 10 11 12 13 14 15 16]'''

#當我們想要刪除8的話（索引值為3)
print(np.delete(arr,3))
'''[ 5  6  7  9 10 11 12 13 14 15 16] '''
# 可以看到8不見了

#使用切片的方法，指定切片位置
#當我們想要切掉5~9的時候
print(np.delete(arr,slice(0,5)))
'''[10 11 12 13 14 15 16] '''

[ 5  6  7  8  9 10 11 12 13 14 15 16]
[ 5  6  7  9 10 11 12 13 14 15 16]
[10 11 12 13 14 15 16]


'[10 11 12 13 14 15 16] '

複製陣列：.copy()

In [28]:
import numpy as np
#當我們複製陣列的時候要很小心是否會影響到原本的陣列
#首先來看個例子
a = np.array([1,2,3])
b = a
b[0] = 100 #如果想把ｂ裡面的1改成100
print(b)
print(a)
'''
[100   2   3]
 [100   2   3]'''
# 我們可以看到a的1也同時變為100
print('------------')
# 應該使用.copy()的語法 避免更改到原始值
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(b)
print(a)
'''
[100   2   3]
[1 2 3]'''
# 可以看到使用copy後就不會更改到a的原始數值

[100   2   3]
[100   2   3]
------------
[100   2   3]
[1 2 3]


'\n[100   2   3]\n[1 2 3]'

多個矩陣相加：
 垂直相加 .vstack( )
 水平相加 hstack( )

In [31]:
import numpy as np
# 垂直方向上相加矩陣
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

print(np.vstack([v1,v2])) #先看看兩個矩陣加起來的樣子
print("---------")
print(np.vstack([v1,v2,v1,v2]))
'''
[[1 2 3 4]
 [5 6 7 8]]
---------
[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]'''
print("---------")
#水平方向上相加矩陣
h1 = np.zeros((2,4))
h2 = np.zeros((2,2))
arr=np.hstack((h1,h2))
'''array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])'''
print(arr)

[[1 2 3 4]
 [5 6 7 8]]
---------
[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]
---------
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


用三維度陣列練習基礎語法

In [34]:
import numpy as np
b= np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)
'''
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]'''

# []內的索引值要從外到內寫
# 如果想要查到4
# 從第1個維度的第0個row > 第2個維度的第1個索引值 > 第3個維度的第２個索引值
print(b[0,1,1])
'''４'''

# get more fancy
print(b[:,0,:]) # 第1個維度的全部 > 第2個維度的第0個索引值 > 第3個維度的全部
print("-----")
print(b[:,0,0]) # 第1個索引值的全部 > 第2個維度的第0個索引值 > 第3個維度的第0個索引值
'''
[[1 2]
 [5 6]]
-----
[1 5]'''
# 先隨便找一個位置
print(b[:,1,:]) # 看他長怎樣
'''
[[3 4]
 [7 8]]'''

#當我們發現他是2*2的陣列時，替換成隨意的他值
b[:,1,:] = [[9,9],[8,8]]
print(b) #重新看b印出來會怎樣
'''
 [[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]
'''

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
4
[[1 2]
 [5 6]]
-----
[1 5]
[[3 4]
 [7 8]]
[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


'\n [[[1 2]\n  [9 9]]\n\n [[5 6]\n  [8 8]]]\n'