[{DAY 12} NumPy 學習筆記(上） - iT 邦幫忙::一起幫忙解決難題，拯救 IT 人的一天](https://ithelp.ithome.com.tw/articles/10262518)
首先要先import 套件
```
import numpy as np
```

In [3]:
import numpy as np
# 建立一維陣列
a=np.array([1,2,3])
print(a)

# 建立二維陣列
b= np.array([[5,3,6,7,1],[1,2,3,4,5]])
print(b)

#將list 換成numpy array:
km_list =[3,5,10,21,42.195]
km_array=np.array(km_list)
print(km_array)

[1 2 3]
[[5 3 6 7 1]
 [1 2 3 4 5]]
[ 3.     5.    10.    21.    42.195]


產生指定數字範圍的陣列：np.arange(起始,結束)

In [4]:
import numpy as np
# 產生數字範圍
arr1=np.arange(10) #從0到9
print(arr1)
arr2=np.arange(3,11)
print(arr2)

[0 1 2 3 4 5 6 7 8 9]
[ 3  4  5  6  7  8  9 10]


產生都是1或都是0的陣列：np.zeros(), np.ones()

In [6]:
import numpy as np
#產生3.5裡面數值皆為0的陣列
print(np.zeros((3,5))) 
print('-----------------')
# 也可以指定元素的type
print(np.ones((4,2,2),dtype="int32"))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
-----------------
[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]


產生填滿指定數字的陣列: np.full((the shape),the value)

In [6]:
import numpy as np
#上面我們看到內建可以創造都是0或1的語法，如果我們想要創其他數值的話
#可以使用np.full((the shpae),the value)
#當我們想創建填滿99的3*3陣列
d=np.full((3,3),99)
print(d)
print('-----------------')
#陣列的shape也可以用已經使用過的其他陣列的形狀
#語法是.full_like(陣列名稱, 數值）
#先創立一個叫做a的2*7陣列
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
#想要創造跟a一樣形狀的陣列，只需要更改變數
#假如我想要創造一個跟a一樣形狀，裡面數值皆為5的陣列
e=np.full_like(a, 5)
print(e)

[[99 99 99]
 [99 99 99]
 [99 99 99]]
-----------------
[[5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5]]


e. 產生隨機陣列： .random.rand(shape)

產生指定在數值範圍內＋指定形狀： random.randint(startvalue, endvalue, size=()）

產生identity matrix : .identity( )

In [8]:
import numpy as np
a=np.identity(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


複製陣列： .repeat( )

In [9]:
import numpy as np
# 當我們想要複製一維陣列幾次時
arr = np.array([[1,2,3,4]]) #當我們想看到[1,2,3,4]以row的形式出現三行時
r1 = np.repeat(arr,3,axis=0) #使用.repeat(陣列名稱，複製的次數，依照什麼維度) 
print(r1)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


取得陣列的資訊

In [13]:
import numpy as np
# 建立一維陣列
a=np.array([1,2,3])

# 建立二維陣列
b= np.array([[5,3,6,7,1],[1,2,3,4,5]])
#取得維度資訊
print(a.ndim) 
print(b.ndim)
print('-----------------')
# 使用.shape
print(a.shape) #因為a只有一維度（一個row)
print(b.shape) #因為b是2*5的二維矩陣
print('-----------------')
# 先建立原本的
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

# 改變成任意形狀
after = before.reshape((8,1)) #改成8*1的矩陣
print(after)


1
2
-----------------
(3,)
(2, 5)
-----------------
[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
-----------------
int32
int32


取得元素的資料型別: .dtype

In [22]:
import numpy as np
# 建立一維陣列
a=np.array([1,2,3])
b= a.astype(np.int64)
# 取得資料型態
print(b.dtype)
#int64

#改變資料型態
change = a.astype(np.float64) #指定他要變成浮點數的型態
print(change.dtype) #印出來檢查看看
#float64

int64
float64
